### ISSUE TITLE
DHCHAP authentication fails with --device parameter when using config-based keys

### ISSUE THREAD

**Issue by puspaksahu-Nuta** [linux-nvme/libnvme#1087]
## Summary

DHCHAP authentication fails when using config-based DHCHAP host keys from `/etc/nvme/config.json` in the presence of discovery controllers. The `nvme_scan_ctrl()` function unconditionally overwrites config-based DHCHAP host keys with NULL when scanning discovery controllers that have `dhchap_secret="none"` in sysfs.

This issue affects unidirectional authentication where only the host authenticates to the target using the DHCHAP host key (`dhchap_key`).

## Environment

- libnvme: v1.11.1
- nvme-cli: v2.11
- Kernel: 5.14.0+
- Transport: TCP (affects all transports)

### Configuration

Create `/etc/nvme/config.json` with DHCHAP key:

```json
[
  {
    "hostnqn": "nqn.2014-08.org.nvmexpress:uuid:148cfdaf-29ba-4f79-6ece-fa55c4b084df",
    "hostid": "66eb7d23-3925-47c5-a3c0-0f6ebae6d76c",
    "dhchap_key": "DHHC-1:00:I5cApohpALDlFqz+gGwbq4PYTwFznfHwzjn6nFBZc7uc7QhK:",
    "subsystems": [
      {
        "nqn": "nqn.2023-10.com.nutanix:test-vg-458ec7c3-0575-43a4-b2aa-028f06250f5c",
        "ports": [
          {
            "transport": "tcp",
            "traddr": "10.46.32.108",
            "trsvcid": "4420",
            "dhchap_ctrl_key": "DHHC-1:00:mbMP0ul6pGFu1AgMneOkeVQs0mK5uEVmeikPg6d6UtziGssj:"
          },
          {
            "transport": "tcp",
            "traddr": "10.46.32.109",
            "trsvcid": "4420",
            "dhchap_ctrl_key": "DHHC-1:00:mbMP0ul6pGFu1AgMneOkeVQs0mK5uEVmeikPg6d6UtziGssj:"
          }
        ]
      }
    ]
  }
]
```

### Scenario: Adding new paths with existing discovery controller

```bash
# Initial connection works fine (without --device)
$ nvme connect-all -t tcp -a 10.46.32.108 -s 4420
# Successfully connects nvme0 (discovery), nvme1, nvme2

$ ls /sys/class/nvme/
nvme0  nvme1  nvme2

# Check discovery controller
$ cat /sys/class/nvme/nvme0/subsysnqn
nqn.2014-08.org.nvmexpress.discovery

$ cat /sys/class/nvme/nvme0/dhchap_secret
none

# Try to add new path using existing discovery controller WITH --device
# This can be triggered manually or automatically via AEN (Asynchronous Event Notification)
# When AEN is received, udev rule triggers nvmf-connect@.service which calls:
# nvme connect-all --device=nvme0 --transport=tcp --traddr=... --trsvcid=...
$ nvme connect-all --device=nvme0
Failed to connect to nvme3: DHCHAP authentication required but no key provided
```

**Kernel logs showing the failure** (from AEN-triggered connection attempt):
```
Sep 24 06:57:13 localhost systemd[1]: Started NVMf auto-connect scan upon nvme discovery controller Events.
Sep 24 06:57:13 localhost sh[496989]: ctrl device nvme0 found, ignoring non matching command-line options
Sep 24 06:57:13 localhost kernel: nvme nvme3: failed to connect socket: -111
Sep 24 06:57:13 localhost kernel: nvme nvme3: qid 0: no key
Sep 24 06:57:13 localhost kernel: nvme nvme3: qid 0: authentication setup failed
Sep 24 06:57:13 localhost kernel: nvme nvme3: failed to connect queue: 0 ret=-126
Sep 24 06:57:13 localhost systemd[1]: nvmf-connect@--device\x3dnvme0\t--transport\x3dtcp\t--traddr\x3d10.46.32.116\t--trsvcid\x3d8009\t--host-traddr\x3dnone\t--host-iface\x3dnone.service: Deactivated successfully.
```

**Expected**: New path (nvme3) connects successfully using config-based key

**Actual**: Connection fails with "qid 0: no key" because config key was destroyed when scanning nvme0

## Root Cause

The issue occurs specifically when using `--device=nvme0` parameter. In this code path, `nvme_scan_ctrl()` is called on the discovery controller before attempting new connections.

In `src/nvme/tree.c`, `nvme_scan_ctrl()` at lines 2199-2210:

```c
if (h) {
    if (h->dhchap_key)
        free(h->dhchap_key);
    h->dhchap_key = nvme_get_attr(path, "dhchap_secret");
    if (h->dhchap_key && !strcmp(h->dhchap_key, "none")) {
        free(h->dhchap_key);
        h->dhchap_key = NULL;  // Config key destroyed
    }
}
```

This unconditionally overwrites `h->dhchap_key` with sysfs value, even when sysfs contains "none".

Discovery controllers always have `dhchap_secret="none"` in sysfs because DHCHAP keys are intentionally not sent to them (per NVMe-oF spec). See `build_options()` in `src/nvme/fabrics.c` lines 665-668:

```c
(!discover && hostkey &&
 add_argument(r, argstr, dhchap_secret, hostkey))
```

The `!discover` condition prevents keys from being sent to discovery controllers.

All controllers with the same hostnqn share a single `nvme_host_t` object. When nvme0 (discovery) is scanned, it destroys the DHCHAP host key for all controllers sharing that host.

## Proposed Fix

Modify `nvme_scan_ctrl()` to only update `h->dhchap_key` when sysfs provides a valid key:

```c
if (h) {
    _cleanup_free_ char *sysfs_key = NULL;
    
    sysfs_key = nvme_get_attr(path, "dhchap_secret");
    /* Only update dhchap_key if sysfs provides a valid value */
    if (sysfs_key && strcmp(sysfs_key, "none")) {
        if (h->dhchap_key)
            free(h->dhchap_key);
        h->dhchap_key = strdup(sysfs_key);
    }
    /* Otherwise: preserve existing h->dhchap_key from config */
}
```

This preserves config-based DHCHAP host keys when sysfs has "none" or NULL, while still allowing sysfs to override with keys from active connections. This ensures unidirectional authentication works correctly when using config-based keys.

Patch available for submission.

**Comment by igaw** [comment]
Test with the latest version. IIRC, we already addressed this.

**Comment by puspaksahu-Nuta** [comment]
Hi @igaw,
Even in the latest version v1.15, I am seeing similar issue.
Its not fixed in the latest master also.

**Comment by igaw** [comment]
I remember why I though we fixed this: a343ed620a4f ("tree: always set the host key"). Yep, makes sense not to kill the secret in the tree.

Though this here is more about fe89efaf3250 ("tree: do not set dhchap_key to 'none'") not handling your use. But there are more than just this one place where the check is not correct. And we have more secrets not just this one. 

Care to send a full patch/PR for this?

**Comment by puspaksahu-Nuta** [comment]
Hi @igaw ,
I've analyzed the codebase to address your concern about "more than 
just this one place" needing fixes:

In the current master branch, only nvme_scan_ctrl() has this issue. 
The other locations from fe89efa ("tree: do not set dhchap_key to 'none'") have been removed during refactoring:
- nvme_scan_subsystem() was completely rewritten
- nvme_configure_ctrl() no longer exists

The nvme_read_sysfs_dhchap() function already has the correct logic  for both dhchap_secret and dhchap_ctrl_secret - it only updates when sysfs provides a valid value, preserving config-based keys.

Regarding "more secrets": I checked dhchap_key, dhchap_ctrl_key, and TLS keys. The dhchap_ctrl_key is already handled correctly in nvme_read_sysfs_dhchap(), and TLS keys are numeric IDs so they don't have the "none" string issue.

If there are other places I've missed that need similar fixes, please let me know and I'll update the patch accordingly.
